**NumPy** is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [4]:
# Importing NumPy

import numpy as np

**1-Dimensional** Array

In [5]:
# For Integers
a = np.array([1,2,3])
# Priting array
print(a)
# Priting Shape of array
print(a.shape)
# Priting specific array element
print(a[0], a[1], a[2])
# Changing any Specific Value
a[0] = 5
print(a)

[1 2 3]
(3,)
1 2 3
[5 2 3]


**2-Dimensional** Array

In [7]:
# For Integers
b = np.array([[1,2,3],
             [4,5,6]])
# Priting array
print(b)
# Priting Shape of array
print(b.shape)
# Priting specific array element
print(b[0,0])

# For Float Values
c = np.array([1.0, 2.1, 3.4])
print(c)

[[1 2 3]
 [4 5 6]]
(2, 3)
1
[1.  2.1 3.4]


**NumPy** provides many different functions for creating arrays.
Say, Array that is _filled with zeros._

In [8]:
a = np.zeros([2,3]) # Parameters Passed --> Size of Array
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


Similarly, We can create an array that is _filled with ones._

In [9]:
b = np.ones([1,2]) # Parameters Passed --> Size of Array
print(b)

[[1. 1.]]


An array that is _filled with some constant value._

In [10]:
c = np.full([2,3], 7) # Parameters Passed --> Size of Array and constant value
print(c)

[[7 7 7]
 [7 7 7]]


An array that is _filled with random values between zero and one._

In [11]:
e = np.random.random([3,7]) # Parameters Passed --> Size of Array
print(e)

[[0.7976333  0.15291034 0.22342737 0.42149542 0.35950892 0.20902477
  0.81097467]
 [0.02697438 0.96632923 0.85635025 0.62777041 0.86438773 0.66063786
  0.20622985]
 [0.22487328 0.00347625 0.73775016 0.23920403 0.08869676 0.94489174
  0.04667409]]


Array indexing using **NumPy**, it offers several ways to index arrays similar to python lists it can also be sliced since arrays may be multi-dimensional.We must specify a slice for each dimension of the array.

In [14]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(a)

b = a[:2, 1:3]
print(b)

print(a[0,1])
b[0,0] = 75
print(a[0,1])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
75
[[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(a)

print(a > 2)

print(a[a > 2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


**Numpy** Basic Array math, Basic math functions operates Elements Y's on arrays. This means that an element and one array corresponds to an element in another array in the same position.

In [26]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

print(np.add(x, y))

print(np.subtract(x, y))

print(np.multiply(x, y))

print(np.divide(x, y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
print(np.sum(x))

print(np.sum(x, axis=0))

print(np.sum(x, axis=1))

10
[4 6]
[3 7]
